# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dashboard.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(970, 723)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("#Background {\n"
"    border: 1px solid black;\n"
"    border-radius: 15px;    \n"
"}\n"
"\n"
"#Header {\n"
"    border: 1px solid black;\n"
"    border-radius: 15px;    \n"
"}\n"
"\n"
"#Top {\n"
"    border: 0px solid black;\n"
"    border-radius: 15px;\n"
"}\n"
"\n"
"#Bottom {\n"
"    border: 2px solid black;\n"
"    border-radius: 15px;\n"
"}\n"
"\n"
"#Video {\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"#SpeciesContainer {\n"
"    border: 2px solid black;\n"
"    border-radius: 15px;\n"
"}\n"
"\n"
"#listWidget {\n"
"    background-color: transparent\n"
"}\n"
"")
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.Background = QtWidgets.QWidget(self.centralwidget)
        self.Background.setMinimumSize(QtCore.QSize(800, 600))
        self.Background.setStyleSheet("")
        self.Background.setObjectName("Background")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.Background)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Header = QtWidgets.QWidget(self.Background)
        self.Header.setMinimumSize(QtCore.QSize(0, 50))
        self.Header.setMaximumSize(QtCore.QSize(16777215, 50))
        self.Header.setObjectName("Header")
        self.verticalLayout.addWidget(self.Header)
        self.Top = QtWidgets.QWidget(self.Background)
        self.Top.setMinimumSize(QtCore.QSize(800, 500))
        self.Top.setObjectName("Top")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.Top)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Video = QtWidgets.QLabel(self.Top)
        self.Video.setAlignment(QtCore.Qt.AlignCenter)
        self.Video.setObjectName("Video")
        self.horizontalLayout.addWidget(self.Video)
        self.SpeciesContainer = QtWidgets.QWidget(self.Top)
        self.SpeciesContainer.setMinimumSize(QtCore.QSize(200, 0))
        self.SpeciesContainer.setMaximumSize(QtCore.QSize(250, 16777215))
        self.SpeciesContainer.setObjectName("SpeciesContainer")
        self.listWidget = QtWidgets.QListWidget(self.SpeciesContainer)
        self.listWidget.setGeometry(QtCore.QRect(20, 30, 211, 431))
        self.listWidget.setObjectName("listWidget")
        self.horizontalLayout.addWidget(self.SpeciesContainer)
        self.verticalLayout.addWidget(self.Top)
        self.Bottom = QtWidgets.QWidget(self.Background)
        self.Bottom.setMinimumSize(QtCore.QSize(800, 100))
        self.Bottom.setMaximumSize(QtCore.QSize(16777215, 100))
        self.Bottom.setObjectName("Bottom")
        self.verticalLayout.addWidget(self.Bottom)
        self.horizontalLayout_2.addWidget(self.Background)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Video.setText(_translate("MainWindow", "Video is here"))
