TARGET_SAMPLING_RATE_HZ = 32000
CLIP_DURATION_S = 3
MIN_AUDIO_LENGTH_S = 60
OVERLAP_PERCENTAGE = 1/3
CLIP_SIZE = CLIP_DURATION_S * TARGET_SAMPLING_RATE_HZ
OVERLAP_SIZE = int(CLIP_SIZE * OVERLAP_PERCENTAGE)
STEP_SIZE = CLIP_SIZE - OVERLAP_SIZE